name: nompangs
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  speech_to_text: ^7.0.0
  http: ^1.3.0
  flutter_dotenv: ^5.2.1
  google_generative_ai: ^0.4.6
  intl: ^0.20.2
  shared_preferences: ^2.5.2
  audioplayers: ^6.4.0
  mobile_scanner: ^7.0.0
  qr_flutter: ^4.1.0
  share_plus: ^7.2.1
  path_provider: ^2.1.5
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  google_sign_in: ^6.3.0
  app_links: ^6.4.0
  permission_handler: ^12.0.0+1
  camera: ^0.10.5+5
  image_picker: ^1.0.4
  provider: ^6.1.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  go_router: ^12.1.3
  lottie: ^2.7.0
  gal: ^2.3.0
  carousel_slider: ^4.2.1
  # just_audio: ^0.10.4
  # audio_session: ^0.2.2
  openai_realtime_dart: ^0.0.4
  sqflite: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/ui_assets/
    - assets/ui_assets/cardShape_1.png
    - assets/ui_assets/cardShape_2.png
    - assets/ui_assets/cardShape_3.png
    - assets/ui_assets/placeHolder_1@2x.png
    - .env
    - assets/google_icon.png
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Regular.ttf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700
